language: node_js

node_js: '10.0.0'

git:
  quiet: true
  submodules: false
  depth: 1

branches:
  only:
    - master

[skip travis]: update README

cache:
  yarn: true

stages:
  - test
  - build
  - deploy
  - name: deploy
    if: branch = master

install: yarn

jobs:
  include:
    - stage: test
      script: yarn test --coverage && cat ./coverage/lcov.info | npx coveralls && rm -rf ./coverage
    - stage: deploy
      before_deploy: yarn build
      script: skip
      deploy: &npm
        provider: npm
        skip_cleanup: true
        email: $email
        api_key: $token
